# yamllint disable rule:line-length
---
init:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
install:
  - appveyor DownloadFile https://github.com/EA31337/MT-Platforms/releases/download/5.0.0.2361/mt-5.0.0.2361.zip && unzip -q *.zip && cp -v */metaeditor*.exe .
  - scoop install ruby python
before_test:
  - chcp
  - ruby --version
  - git submodule update --init
test_script:
  - metaeditor64 /s /compile:. /log:mql.log || exit /b 0
  - type mql.log
  - ruby -e "if File.open('mql.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9] error'.encode(Encoding::UTF_16LE)) {exit 1}; end"
  - ruby -e "if File.open('mql.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9] warning'.encode(Encoding::UTF_16LE)) {exit 1}; end"
  - ruby -e "if File.open('mql.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9][0-9] error'.encode(Encoding::UTF_16LE)) {exit 1}; end"
  - ruby -e "if File.open('mql.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9][0-9] warning'.encode(Encoding::UTF_16LE)) {exit 1}; end"
build: false
platform: x86
