language: generic
services:
  - docker
env:
  matrix:
  - CMD="docker-compose run ConvertTest"
  - CMD="docker-compose run StatsTest"
  - CMD="docker-compose run SummaryReportTest"
  - CMD="docker-compose run TickerTest"
before_script:
- cd tests
script:
- eval $CMD
after_failure:
- docker-compose logs
