language: generic
services:
  - docker
env:
  global:
  - |
    CWD="$TRAVIS_BUILD_DIR"
    DOCKER_REPO=ea31337/ea-tester:dev
  matrix:
  - BT_RUN="compile_ea Convert.mq4 && run_backtest -m1 -e Convert.mq4"
  - BT_RUN="compile_ea Stats.mq4 && run_backtest -m1 -e Stats.mq4"
  - BT_RUN="compile_ea SummaryReport.mq4 && run_backtest -m1 -e SummaryReport.mq4"
  - BT_RUN="compile_ea TickerTest.mq4 && run_backtest -m1 -e TickerTest.mq4"
before_script:
- docker pull $DOCKER_REPO
script:
- docker run -v "$PWD:/opt/EA31337-classes:ro" $DOCKER_REPO 'git clone /opt/EA31337-classes "$EXPERTS_DIR"/EA31337-classes;' $BT_RUN
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
