environment:
  FILELOG: metaeditor.log
install:
- appveyor DownloadFile https://github.com/EA31337/MetaEditor/raw/master/metaeditor.exe
before_test:
- pwd
- chcp
test_script:
- |-
  metaeditor /s /compile:. /inc:.. /log:%FILELOG% || exit /b 0
  type %FILELOG%
  find /I "error(s)" %FILELOG% | findstr /I /R /C:"result 0 error(s), 0 warning(s)" /V && exit /b 1 || exit /b 0
build: off
platform: x86
