---
name: Tests

on:
  - pull_request
  - push

jobs:
  Experts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ActionTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "ActionTest"
          RunOnError: "pwd && tree -sup"
      - name: Run AccountTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "AccountTest"
      - name: Run BufferTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "BufferTest"
      - name: Run ConditionTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "ConditionTest"
      - name: Run DrawIndicatorTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "DrawIndicatorTest"
      - name: Run IndicatorDataTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "IndicatorDataTest"
      - name: Run IndicatorTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "IndicatorTest"
      - name: Run IndicatorsTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "IndicatorsTest"
      - name: Run MailTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "MailTest"
      - name: Run MarketTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "MarketTest"
      - name: Run OrderTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "OrderTest"
      - name: Run StatsTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "StatsTest"
      - name: Run StrategyTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "StrategyTest"
      - name: Run SummaryReportTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "SummaryReportTest"
      - name: Run TaskTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "TaskTest"
      - name: Run TickerTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "TickerTest"
      - name: Run TradeTest
        uses: ea31337/mql-tester-action@master
        with:
          TestExpert: "TradeTest"
  Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run CollectionTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "CollectionTest"
          RunOnError: "pwd && tree -sup"
      - name: Run ConfigTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "ConfigTest"
      - name: Run ConvertTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "ConvertTest"
      - name: Run DictTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "DictTest"
      # @fixme
      - name: Run LogTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "LogTest"
          RunOnFail: "exit 0"
      - name: Run ProfilerTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "ProfilerTest"
      - name: Run TerminalTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "TerminalTest"
      - name: Run TimerTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "TimerTest"
      # @fixme
      - name: Run WebTest
        uses: ea31337/mql-tester-action@master
        with:
          Script: "WebTest"
          RunOnFail: "exit 0"
