---
name: Run Tests

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ActionTest
      working-directory: tests
      run: docker-compose run ActionTest
    - name: Run AccountTest
      working-directory: tests
      run: docker-compose run AccountTest
    - name: Run BufferTest
      working-directory: tests
      run: docker-compose run BufferTest
